version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: openlearn_db
    restart: always
    environment:
      POSTG-RES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openlearn
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: openlearn_adminer
    restart: always
    ports:
      - "8088:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
